default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dualsun_pvmes_development

test:
  <<: *default
  database: dualsun_pvmes_test

production:
  <<: *default
  database: dualsun_pvmes_production
  username: dualsun_pvmes_api
  password: <%= ENV["DUALSUN_PVMES_PASSWORD"] %>
